stages:
  - testing
  - publishing

.testing_template: &python_matrix
  stage: testing
  script:
    - make install-development
    - make coverage
  artifacts:
    paths:
      - htmlcov
    expire_in: 3 days

coverage:py36:
  <<: *python_matrix
  image: python:3.6-buster

coverage:py37:
  <<: *python_matrix
  image: python:3.7-buster

coverage:py38:
  <<: *python_matrix
  image: python:3.8-buster

pages:
  image: debian:buster
  stage: publishing
  dependencies:
    - coverage:py38
  script:
    - rm --force --recursive public
    - cp --recursive htmlcov public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
    - schedules
    - tags
