image: python:3.8-buster

before_script:
  - python --version
  - make install-development

stages:
  - testing
  - coverage
  - publishing

.testing_template: &python_matrix
  stage: testing
  script: make test

.publishing_template: &publishing
  stage: publishing
  dependencies: []

testing:py3.6:
  <<: *python_matrix
  image: python:3.6-buster

testing:py3.7:
  <<: *python_matrix
  image: python:3.7-buster

testing:py3.8:
  <<: *python_matrix

code quality:
  stage: coverage
  needs:
    - testing:py3.6
    - testing:py3.7
    - testing:py3.8
  script: make coverage

build package:
  <<: *publishing
  script: make build
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}
    paths:
      - dist
    expire_in: 1 week
  only:
    - master
    - tags

deployment:
  <<: *publishing
  variables:
    TWINE_USERNAME: ${CI_REGISTRY_USER}
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    TWINE_REPOSITORY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  script: make upload
  only:
    - master

pages:
  <<: *publishing
  script: make docs
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
