image: python:3.8-buster

stages:
  - testing
  - coverage
  - publishing

.testing_template: &python_matrix
  stage: testing
  before_script:
    - python --version
  script:
    - make install-development
    - make test

testing:py3.6:
  <<: *python_matrix
  image: python:3.6-buster

testing:py3.7:
  <<: *python_matrix
  image: python:3.7-buster

testing:py3.8:
  <<: *python_matrix

code quality:
  stage: coverage
  needs:
    - testing:py3.6
    - testing:py3.7
    - testing:py3.8
  script:
    - make install-development
    - make coverage

pages:
  stage: publishing
  script:
    - make install-development
    - make docs
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
    - tags
