stages:
  - testing
  - coverage
  - publishing

.testing_template: &python_matrix
  stage: testing
  script:
    - make install-development
    - make test

testing:py3.6:
  <<: *python_matrix
  image: python:3.6-buster

testing:py3.7:
  <<: *python_matrix
  image: python:3.7-buster

testing:py3.8:
  <<: *python_matrix
  image: python:3.8-buster

code quality:
  image: python:3.8-buster
  stage: coverage
  needs:
    - testing:py3.6
    - testing:py3.7
    - testing:py3.8
  script:
    - make build
    - make install-development
    - make coverage
  artifacts:
    paths:
      - dist/scienco-*.tar.gz
      - dist/scienco-*.tar.xz
      - dist/scienco-*.whl
      - dist/scienco-*.zip
    expire_in: 1 week

pages:
  image: python:3.8-buster
  stage: publishing
  script:
    - make install-development
    - make docs
  dependencies: []
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
    - tags
