stages:
  - testing
  - publishing

.testing_template: &python_matrix
  stage: testing
  script:
    - make install-development
    - make coverage

coverage:py3.6:
  <<: *python_matrix
  image: python:3.6-buster

coverage:py3.7:
  <<: *python_matrix
  image: python:3.7-buster

coverage:py3.8:
  <<: *python_matrix
  image: python:3.8-buster
  artifacts:
    paths:
      - htmlcov
    expire_in: 3 days

pages:
  image: debian:buster
  stage: publishing
  dependencies:
    - coverage:py3.8
  script:
    - rm --force --recursive public
    - cp --recursive htmlcov public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
    - schedules
    - tags
