image: python:3.8-buster

before_script:
  - python --version
  - make install-development

stages:
  - testing
  - coverage
  - publishing

.testing_template: &python_matrix
  stage: testing
  script: make test

testing:py3.6:
  <<: *python_matrix
  image: python:3.6-buster

testing:py3.7:
  <<: *python_matrix
  image: python:3.7-buster

testing:py3.8:
  <<: *python_matrix

code quality:
  stage: coverage
  needs:
    - testing:py3.6
    - testing:py3.7
    - testing:py3.8
  script: make coverage

deployment:
  stage: publishing
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    TWINE_REPOSITORY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  script: make upload
  only:
    - master
    - tags

pages:
  stage: publishing
  script: make docs
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
    - tags
