site_name: Scienco
site_author: Andrew Malchuk
site_description: Calculate the readability of text using one of a variety of computed indexes
site_url: https://amalchuk.gitlab.io/scienco

site_dir: public
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  font:
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: fontawesome/solid/graduation-cap

repo_name: amalchuk/scienco
repo_url: https://gitlab.com/amalchuk/scienco
edit_uri: ""

nav:
  - Introduction: index.md
  - API Reference: api_reference.md
  - Distribution: distribution.md

markdown_extensions:
  - codehilite
